### PR TITLE
Add support for k2 lightcurves

### PR DESCRIPTION
**Pull request by mirca**
I added support for accessing K2 lightcurves. Appreciate any suggestions :D 
cc @rodluger @barentsen

edit:

code snippet:
```
>>> import kplr
>>> k2star = kplr.API().k2_star(247571257)
>>> k2star
<K2Star(247571257)>
>>> k2star.get_light_curves()
[<K2LightCurve("KTWO247571257-C13_LC")>]
```

oops, this patch overlaps with #25

### CODE REVIEW

**Comment by dfm** [comment]
@rodluger: how do you feel about this over #25? It looks like this has the feature you want and more...

**Comment by dfm** [comment]
PS thanks @mirca! I'm on holiday so everything is moving slowly.

**Comment by rodluger** [comment]
@dfm: This one looks good, thanks @mirca. You can close mine!

**Comment by mirca** [comment]
@dfm @rodluger Thanks =D

**Pull request merged**
